# Generated by Django 4.1.3 on 2022-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_whyus_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='klass',
            field=models.CharField(default='long_content', max_length=200),
        ),
    ]
