# Generated by Django 4.1.3 on 2022-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_oav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oav',
            old_name='body',
            new_name='body_1',
        ),
        migrations.RenameField(
            model_name='oav',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='oav',
            old_name='title',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='oav',
            name='body_2',
            field=models.CharField(default='aa', max_length=200),
        ),
        migrations.AddField(
            model_name='oav',
            name='image_2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='oav',
            name='title_2',
            field=models.CharField(default='ss', max_length=200),
        ),
    ]
