# Generated by Django 4.1.3 on 2022-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_body_oav_body_1_rename_image_oav_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'About us item',
                'verbose_name_plural': 'About us items',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Main Product', 'verbose_name_plural': 'Main Products'},
        ),
        migrations.AlterModelOptions(
            name='oav',
            options={'verbose_name': 'OAV item', 'verbose_name_plural': 'OAV items'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name': 'Why us item', 'verbose_name_plural': 'Why us items'},
        ),
    ]
