# Generated by Django 4.1.3 on 2022-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Site Kontakti',
                'verbose_name_plural': 'Site Kontaktlari',
            },
        ),
    ]
