# Generated by Django 4.1.3 on 2022-11-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('shape', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('packing_specifications', models.CharField(max_length=50)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Items',
            },
        ),
    ]
