# Generated by Django 4.1.3 on 2022-11-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='p_name',
            new_name='p_body',
        ),
    ]
